### ISSUE TITLE
Pagination on employee list

### ISSUE THREAD

**Issue by anand-singh** [knoldus/playing-reactive-mongo#1]
Wright now pagination is not working need to implement the pagination logic for employee list.

**Comment by dejvid** [comment]
I too miss pagination .

**Comment by seyuf** [comment]
Hi @anand-singh ,
Im fairly new to reactive mongo, so i would like to know why haven't you considered something like:
```
collection.find(selector).options(QueryOpts((pageNumber - 1)*numberPerPage, numberPerPage)).cursor[JsObject]
```
for the pagination?

**Comment by anand-singh** [comment]
Hi @seyuf ,

Thanks for your idea I will look into this and implement it but if you like to implement it then go ahead and implement it and create a pull request.

Thanks again.

**Comment by pecorarista** [comment]
Commits on Mar 24 seems to have solved this issue.
